# Generated by Django 4.0.4 on 2022-05-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_cartitem_variations'),
        ('orders', '0003_remove_orderproduct_variations'),
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
