# Generated by Django 4.0.4 on 2022-05-13 03:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_id_alter_reviewrating_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 5, 13, 3, 3, 15, 301106, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 5, 13, 3, 3, 15, 301106, tzinfo=utc)),
        ),
    ]
