# Generated by Django 4.0.4 on 2022-05-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_reviewrating_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='created_at',
            field=models.DateTimeField(verbose_name='+07'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='updated_at',
            field=models.DateTimeField(verbose_name='+07'),
        ),
    ]
