# Generated by Django 4.0.4 on 2022-05-13 03:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_reviewrating_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 13, 10, 19, 47, 20218, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 13, 10, 19, 47, 20218, tzinfo=utc)),
        ),
    ]
