# Generated by Django 4.0.4 on 2022-05-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_remove_cartitem_variations'),
        ('orders', '0010_remove_orderproduct_variations'),
        ('store', '0020_alter_reviewrating_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
