# Generated by Django 4.0.4 on 2022-05-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cart_user_alter_cart_id_alter_cartitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
