# Generated by Django 4.0.4 on 2022-05-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_remove_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variations',
        ),
    ]
