# Generated by Django 4.0.4 on 2022-05-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_is_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
