# Generated by Django 4.0.4 on 2022-05-10 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_payment_order_payment_orderproduct_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='country',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='ward',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_line_2',
        ),
    ]
